import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar from "../Components/Navbar.jsx"
import  Header from "../Components/Header.jsx"
import About from "../Components/About"
import Services from "../Components/Services"
import Projects from "../Components/Projects"
import Experience from "../Components/Experience"
import Contact from "../Components/Contact"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Enid Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Header/>
      <About/>
      <Services/>
      <Experience/>
      <Projects/>
      <Contact/>
    </div>
  )
}
