import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar from "../Components/Navbar.jsx"
import  Header from "../Components/Header.jsx"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Enid Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Header/>
    </div>
  )
}
